from pathlib import Path
import argparse

ap=argparse.ArgumentParser(); ap.add_argument('--source-root',required=True); ap.add_argument('--output-dir',required=True); a=ap.parse_args()
out=Path(a.output_dir); p=out/'controller.cpp'
raw=p.read_bytes(); text=raw.decode('utf-8-sig'); nl='\r\n' if '\r\n' in text else '\n'; t=text.replace('\r\n','\n').replace('\r','\n')

def once(old,new,label):
    global t
    c=t.count(old)
    if c!=1: raise SystemExit(f'{label}: expected one marker, found {c}')
    t=t.replace(old,new,1)

old_gather='''    void TickGatherAccount(Account& a, DWORD now) {\n        if (!gatherModeActive_ || !IsGatherPid(a.game.pid) || !a.runtime.running) return;\n        if (!gatherTarget_.valid) { a.runtime.status = L"TẬP TRUNG • mất tọa đích • fail-closed"; return; }\n        const Snapshot& s = a.snapshot;\n        if (!s.mapReady || s.waitingChangeMap) { a.runtime.status = L"TẬP TRUNG • đang chuyển map"; return; }\n        const std::uint32_t need = ValidMap | ValidPosition | ValidRiding | ValidAutoPath;\n        if ((s.validMask & need) != need) { a.runtime.status = L"TẬP TRUNG • chờ state"; return; }\n        if (HandleDeath(a, now)) return;\n        if (HandleRouteOwnershipReset(a, now)) return;\n        bool arrived = false;\n        (void)HandleRobustTravel(a, now, gatherTarget_, L"điểm tập trung", arrived);\n        if (arrived) {\n            a.runtime.status = L"TẬP TRUNG • ĐÃ TỚI • tiếp tục check tọa";\n        }\n    }\n'''
new_gather='''    void TickGatherAccount(Account& a, DWORD now) {\n        if (!gatherModeActive_ || !IsGatherPid(a.game.pid) || !a.runtime.running) return;\n        if (!gatherTarget_.valid) { a.runtime.status = L"TẬP TRUNG • mất tọa đích • fail-closed"; return; }\n        const Snapshot& s = a.snapshot;\n        if (!s.mapReady || s.waitingChangeMap) { a.runtime.status = L"TẬP TRUNG • đang chuyển map / chờ xác nhận nếu route yêu cầu"; return; }\n        const std::uint32_t need = ValidMap | ValidPosition | ValidRiding | ValidAutoPath | ValidAutoFight;\n        if ((s.validMask & need) != need) { a.runtime.status = L"TẬP TRUNG • chờ Map/X/Y/Ngựa/Path/AutoFight authoritative"; return; }\n        if (HandleDeath(a, now)) return;\n        if (HandleRouteOwnershipReset(a, now)) return;\n        if (HandleUnderworldAutoFightGuard(a, now)) return;\n\n        State gatherLogic{};\n        gatherLogic.valid = true; gatherLogic.mapReady = true; gatherLogic.waitingMap = false;\n        gatherLogic.mapID = s.mapID; gatherLogic.x = s.x; gatherLogic.y = s.y;\n        gatherLogic.riding = s.riding != 0; gatherLogic.autoPathing = s.autoPathing != 0;\n        Target gatherWorld{gatherTarget_.mapID, gatherTarget_.x, gatherTarget_.y, a.profile.tolerance};\n        const bool alreadyAtGather = AtTarget(gatherLogic, gatherWorld);\n\n        // Gather is a temporary common training target, not a special movement shortcut.\n        // Before leaving the current point use the same hard route contract as normal train:\n        // AutoFight OFF -> mount -> AutoPath. HandleRobustTravel keeps shortcut/map-confirm logic intact.\n        if (!alreadyAtGather && s.autoFight) {\n            if (!EnsureAutoFightOffForTravel(a, now, L"TẬP TRUNG • tắt AutoFight trước khi rời điểm hiện tại")) {\n                a.runtime.status = L"TẬP TRUNG • tắt AutoFight trước → sau đó mới lên ngựa/AutoPath";\n                return;\n            }\n        }\n\n        bool arrived = false;\n        (void)HandleRobustTravel(a, now, gatherTarget_, L"bãi tập trung", arrived);\n        if (!arrived) return;\n\n        // At the shared target, behave like a normal training spot: enable AutoFight with\n        // the existing P3 AUTO->Đánh quái sequence (when that account has enableFight).\n        if (HandleFightClicks(a, now)) {\n            if ((a.snapshot.validMask & ValidAutoFight) && a.snapshot.autoFight)\n                a.runtime.status = L"TẬP TRUNG • ĐÚNG BÃI CHUNG • AutoFight ON • tiếp tục check tọa";\n            return;\n        }\n        a.runtime.status = L"TẬP TRUNG • ĐÚNG BÃI CHUNG • tiếp tục check tọa";\n    }\n'''
once(old_gather,new_gather,'cp6 gather uses complete train route/fight contract')

old_sched='''                if (!gatherModeActive_ && !partyBuildModeActive_ && a.runtime.priorityAutoRequestSlot != ClickSlot::None) {\n                    (void)PriorityAutoClick(a);\n                }\n'''
new_sched='''                if (!partyBuildModeActive_ && a.runtime.priorityAutoRequestSlot != ClickSlot::None &&\n                    (!gatherModeActive_ || (gatherModeActive_ && IsGatherPid(a.game.pid)))) {\n                    // Gather is a temporary common train spot, so P3 AUTO->Đánh quái is\n                    // allowed only for gather-owned PIDs after they reach the shared target.\n                    (void)PriorityAutoClick(a);\n                }\n'''
once(old_sched,new_sched,'cp6 allow P3 fight for gather-owned clients')

old_complete='''    void CompletePartyBuildIfDone() {\n        if (!partyBuildModeActive_) return;\n        for (const auto& s : partyBuildSessions_) if (s.phase != PartyBuildPhase::Done) return;\n        std::wstring summary = L"AUTO TẠO PT HOÀN TẤT\\r\\n\\r\\n";\n        bool allPass = true;\n        for (const auto& line : partyBuildPreflightSummary_) { summary += line + L"\\r\\n"; allPass = false; }\n        for (const auto& s : partyBuildSessions_) {\n            summary += PartySessionSummary(s) + L"\\r\\n";\n            if (s.failed != 0) allPass = false;\n        }\n        partyBuildModeActive_ = false;\n        partyBuildSessions_.clear();\n        for (auto& item : accounts_) if (item->runtime.running) StopAccount(*item);\n        SetTradeStatus(L"TỰ TẠO PT OFF • tool IDLE • không tự START lại auto cũ");\n        Log(L"TỰ TẠO PT OFF • hoàn tất; tool IDLE; không tự START lại auto cũ.");\n        UpdatePartyBuildToggleLabel();\n        MessageBoxW(hwnd_, summary.c_str(), L"AUTO TẠO PT HOÀN TẤT", MB_OK | (allPass ? MB_ICONINFORMATION : MB_ICONWARNING));\n    }\n'''
new_complete='''    void CompletePartyBuildIfDone() {\n        if (!partyBuildModeActive_) return;\n        for (const auto& s : partyBuildSessions_) if (s.phase != PartyBuildPhase::Done) return;\n        std::wstring detail = L"AUTO PT CHI TIẾT";\n        bool allPass = true;\n        for (const auto& line : partyBuildPreflightSummary_) { detail += L"\\r\\n" + line; allPass = false; }\n        for (const auto& s : partyBuildSessions_) {\n            detail += L"\\r\\n" + PartySessionSummary(s);\n            if (s.failed != 0) allPass = false;\n        }\n        Log(detail);\n        partyBuildModeActive_ = false;\n        partyBuildSessions_.clear();\n        for (auto& item : accounts_) if (item->runtime.running) StopAccount(*item);\n        SetTradeStatus(L"TỰ TẠO PT OFF • tool IDLE • không tự START lại auto cũ");\n        Log(L"TỰ TẠO PT OFF • hoàn tất; tool IDLE; không tự START lại auto cũ.");\n        UpdatePartyBuildToggleLabel();\n        MessageBoxW(hwnd_, allPass ? L"XONG" : L"CHƯA XONG", L"TỰ TẠO PT",\n                    MB_OK | (allPass ? MB_ICONINFORMATION : MB_ICONWARNING));\n    }\n'''
once(old_complete,new_complete,'cp6 minimal party completion popup')

old_empty='''        if (partyBuildSessions_.empty()) {\n            std::wstring msg = L"AUTO TẠO PT: không có PT hợp lệ để chạy.";\n            for (const auto& line : partyBuildPreflightSummary_) msg += L"\\r\\n" + line;\n            SetTradeStatus(L"TỰ TẠO PT OFF • tool IDLE");\n            MessageBoxW(hwnd_, msg.c_str(), L"AUTO TẠO PT", MB_OK | MB_ICONWARNING);\n            UpdatePartyBuildToggleLabel();\n            return;\n        }\n'''
new_empty='''        if (partyBuildSessions_.empty()) {\n            Log(L"AUTO PT CHI TIẾT • không có PT hợp lệ để chạy.");\n            for (const auto& line : partyBuildPreflightSummary_) Log(line);\n            SetTradeStatus(L"TỰ TẠO PT OFF • tool IDLE");\n            MessageBoxW(hwnd_, L"CHƯA XONG", L"TỰ TẠO PT", MB_OK | MB_ICONWARNING);\n            UpdatePartyBuildToggleLabel();\n            return;\n        }\n'''
once(old_empty,new_empty,'cp6 minimal no-valid-party popup')

p.write_bytes(t.replace('\n',nl).encode('utf-8'))
print('apply_v99_automation_cp6.py: PASS')
